import type { Metadata } from 'next'
import React from 'react'
//theme
import 'primereact/resources/themes/lara-light-indigo/theme.css'
//core
import 'primereact/resources/primereact.min.css'

import 'primeicons/primeicons.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <main className=''>{children}</main>
  )
}
